Fact.create(body: 'Cats are the most popular pet in the United States: There are 88 million pet cats and 74 million dogs.', author_name: 'Joe Biden')
Fact.create(body: 'There are cats who have survived falls from over 32 stories (320 meters) onto concrete.', author_name: 'Patrick Leahy')
Fact.create(body: 'A group of cats is called a clowder.', author_name: 'Harry Reid')
Fact.create(body: 'Cats have over 20 muscles that control their ears.', author_name: 'Dick Durbin')
Fact.create(body: 'Cats sleep 70% of their lives.', author_name: 'Chuck Schumer')
Fact.create(body: 'A cat has been mayor of Talkeetna, Alaska, for 15 years. His name is Stubbs.', author_name: 'Patty Murray')
Fact.create(body: 'And one ran for mayor of Mexico City in 2013.', author_name: 'Michael Bennet')
Fact.create(body: 'In tigers and tabbies, the middle of the tongue is covered in backward-pointing spines, used for breaking off and gripping meat.', author_name: 'Debbie Stabenow')
Fact.create(body: 'When cats grimace, they are usually “taste-scenting.” They have an extra organ that, with some breathing control, allows the cats to taste-sense the air.', author_name: 'Mark Begich')
Fact.create(body: 'Cats can’t taste sweetness.', author_name: 'Mitch McConnell')